### ISSUE TITLE
Error with make carla 

### ISSUE THREAD

**Issue by aureliuszi** [HARPLab/DReyeVR#13]
![carla-error-r](https://user-images.githubusercontent.com/25374562/165104532-8a24cfca-9eac-4784-9793-056bc10bdbe2.png)

Hi!

This issue is solved, but logging it here in case it is helpful to others.

I am using a Windows machine.

I had an error with the first ("make carla") command of DReyeVR after cloning DReveVR via GitHub desktop. Once I recloned DReyeVR with WSL, as Gustavo advised, this error went away.

**Comment by GustavoSilvera** [comment]
@aureliuszi thanks for the note! Yeah, when you `git clone` something in Windows CMD (ie. batch) or GitHub desktop the default behaviour is to [convert the files to the host machine's file ending format](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) (LF for Unix-line, CRLF for MS-DOS). Therefore, since our bash scripts are expected to to be in LF mode, you might run into these `\r` errors unless you clone from WSL (or another bash terminal). 


This is a good note to make, we'll probably work on either batch scripts or a better method for installation on Windows soon.
