### ISSUE TITLE
Questions about general understanding of DReyeAR

### ISSUE THREAD

**Issue by sunchongren** [HARPLab/DReyeVR#20]
Hey contributors
I have some confusion about VR version of Carla. 
1. After successfully ```make launch``` and ```make package```, a new folder was created in ```carla/Build```. Do we need to do any operation inside this folder or in carla root folder
2. The carla has server side and client side. When I run a normal version of carla, the server side is like an overview of the whole map. Hoever, for DReyeVR, the server side is the view inside a Tesla (image below). I am confused about this.
![image](https://user-images.githubusercontent.com/92778466/165600582-df1344c3-2976-4d56-b16a-3627b2a3cd1e.png)
3.

**Comment by GustavoSilvera** [comment]
Hi @sunchongren good questions!

1. `make launch` will build a "debug mode" of the simulator where the UE4 editor opens and you can do development work on CARLA/DReyeVR. `make package` builds an optimized "release mode" executable in `carla/Build/CarlaUE4/` so you can do everything within that folder. You can even move that build folder out and use it as a standalone application.
2. The CARLA server has a server side and client side, yes. In vanilla CARLA, when you run `CarlaUE4.exe` then you are placed in a "floating camera" view and can fly around the world. Then all interactions are done via the PythonAPI to control the spawned ego-vehicles and spawn other vehicles and so forth. 

Since we are using Unreal's VR implementation, we instead chose to have the ego-vehicle be a default part of the server (UE4 window) and all interactions can be done directly there (such as the logitech wheel and keyboard inputs). This is better for performance (no python and socket communication) and flexibility as all our code is directly in the engine (See `EgoVehicle.h`)
