### ISSUE TITLE
autopilot cars collide with the stuff in a road 

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#53]
Hi Gustavo this is me again :)
when I set autopilot for the vehicles not DReyeVR vehicle and put some staff on the road vehicles collide to this staff. I do not find any comment about preventing collision for autopilot mode. could you guide me what should I do?

**Comment by GustavoSilvera** [comment]
Hi, can you explain further what the non-ego autopilot behaviour looks like? Are they crashing into pedestrians who are jaywalking or standing in the middle of the road? Or are they crashing into walls/each other as seen in #41 ?

**Comment by FBanani** [comment]
I used generate_traffic.py and change the code in some lines therefore vehicles not crash to each other or walls, and this is the code. 
[adding autopilot vehicles.txt](https://github.com/HARPLab/DReyeVR/files/9243930/adding.autopilot.vehicles.txt)
but I provided the obstacle in the road which is not a car and I do not know how improve the autopilot mode for non-ego vehicles to avoid this obstacle. could you guide me because every thing that I found is for def collision_and_car_avoid_manager(self, waypoint) not for a fixed obstacle?

**Comment by GustavoSilvera** [comment]
This sounds like more of a Carla issue than a DReyeVR issue. 

I'm not sure the vehicle's in carla will automatically stop for anything in their path, since they are blind to all things that have not been registered in the [Carla actor registry](http://carla.org/Doxygen/html/df/db5/classFActorRegistry.html). We get around this by [registering our (DReyeVR) EgoVehicle with the CarlaRegistry](https://github.com/HARPLab/DReyeVR/blob/51ea84a65df001801f582051dc3899d996d3f7b9/DReyeVR/EgoVehicle.cpp#L622-L643). Which might be something you're interested in. 

Another simple option is to use the [line-trace functions provided in the AI controller to detect](https://github.com/carla-simulator/carla/blob/8854804f4d7748e14d937ec763a2912823a7e5f5/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp#L44-L72) when there is something in front of the vehicle and apply the brakes (but this is not "smart" and would not be able to re-route around the obstacle).

**Comment by FBanani** [comment]
thank you so much

**Comment by wx983** [comment]
@GustavoSilvera 
In addition, when I switch to the manual drving through pressing `1` in the keyboard, it can't back up in the `R` mode. Can you fix it?
![image](https://user-images.githubusercontent.com/73030394/221529605-63efd174-ce2b-4759-8392-23538b35fad4.png)

**Comment by GustavoSilvera** [comment]
@wx983 For your first point, I haven't seen this behavior but I also haven't tested the built-in traffic manager autopilot feature very heavily yet, so there could be some bugs in CARLA. Does this behavior also happen for other vehicles on autopilot that are not the EgoVehicle?

For your second point, this sounds like a DReyeVR bug and I'll look into it. But how are you switching gears to reverse? Are you using the keyboard input (`z` or `LAlt`) or using the logitech (face buttons) wheel?

**Comment by wx983** [comment]
> @wx983 For your first point, I haven't seen this behavior but I also haven't tested the built-in traffic manager autopilot feature very heavily yet, so there could be some bugs in CARLA. Does this behavior also happen for other vehicles on autopilot that are not the EgoVehicle?
> 
> For your second point, this sounds like a DReyeVR bug and I'll look into it. But how are you switching gears to reverse? Are you using the keyboard input (`z` or `LAlt`) or using the logitech (face buttons) wheel?

First point, other vehicles on autopilot that are not the EgoVehicle are always able to pass intersections normally. This issue(can not pass intersection) happens for EgoVehicle occassionally. As things should be, both EgoVehicle and other vehicles are `autopilot`. They should behave the same. That's really strange. Next I will also look into it.

Second point, I use Logitech wheel to control EgoVehicle and I use them to reverse gear.
![image](https://user-images.githubusercontent.com/73030394/221600736-03435654-1a91-40a2-a7f4-8b5668138071.png)

**Comment by GustavoSilvera** [comment]
Okay interesting, I will definitely look into the reverse bug. Thanks for letting me know!
